Tienda/Controllers/AccesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

using Tienda.Models;

using System.Data.SqlClient;
using System.Data;
using Tienda.Permisos;

namespace Tienda.Controllers
{
    public class AccesoController : Controller
    {

        
        

        public ActionResult CerrarSesion()
        {
            Session["Cliente"] = null;
            return RedirectToAction("Index", "Home");
        }


    }
}

Tienda/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tienda.Controllers
{
    public class ProductosController : Controller
    {
        //----------------------------VISTA CON LA LISTA DE PRODUCTOS AGREGADOS POR EL EMPLEADO----------------------------
        public ActionResult IndexProductos()
        {


            List<Models.Productos> lstProductos = DAO.Productos.GetAll();
            return View(lstProductos);
        }

      
    }
}

Tienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")




</head>
<body >
  
        <header>

            <nav class="navbar navbar-expand-md navbar-light contenedor" style="background-color:rgb(55 65 81); width: 100%; ">
                <div class="container-fluid">
                    <button class="navbar-toggler contenedor" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse contenedor " id="navbarSupportedContent" style=" background-color: rgb(55 65 81); width: 100% ">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 contenedor" style=" width: 100%; padding-top: 15px; padding-left: 15px">
                            <li class="nav-item ">
                                <span class="nav-link efecto "  style="letter-spacing: 8px; font-size: x-large; ">@Html.ActionLink("CLOTHES DATA", "Index", "Home", null, new { @class = "efecto", @style = "text-decoration:none; " }) </span>

                            </li>

                            <li class="nav-item">
                                <a class="nav-link popover-test" href="#" style="color: rgb(55 65 81); font-size: large; border-radius:1%; border-image: initial; background-color: white; ">Bienvenido a ClothesDada</a>
                            </li>
                            
                            <li class="nav-item">
                                <span class="nav-link Normal " style=" padding-left: 20px; font-size: large; white-space: nowrap; padding-top: 13px">@Html.ActionLink("Nuestros Productos", "IndexProductos", "Productos", null, new { @class = "Normal", @style = "text-decoration:none; " })</span>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link Normal " style=" padding-left: 20px; font-size: large; white-space: nowrap; padding-top: 13px" >@Html.ActionLink("Contactenos", "ContactenosNoRegistrado", "Contacto", null, new { @class = "Normal", @style = "text-decoration:none; " })</span>
                            </li>

                            <li class="nav-item" style="white-space: nowrap;">
                                <span class="nav-link Normal "  style="font-size: calc(2vw); padding-left: 130px; white-space: nowrap; padding-top: 0%">@Html.ActionLink("Iniciar sesión", "LoginCliente", "Cliente", null, new { @class = "Normal", @style = "text-decoration:none; " })</span>

                                <span class="nav-link Normal" style="font-size: calc(1vw); color: white; padding-left: 100px; white-space: nowrap; ">¿No estas Registrado? <span>@Html.ActionLink("Registrate AQUÍ", "RegistrarCliente","Cliente", null, new { @style = "color: cornflowerblue;" })</span></span>

                                
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Tu mundo de confección, ClotesData</p>
            </footer>
        </div>

        @RenderSection("scripts", required: false)
   
</body>
</html>

Tienda/Views/Shared/_LayoutClienteLogeado.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


</head>

<body>


    <div class="back">
        <header style="display:block">

            <nav class="navbar navbar-expand-md navbar-light contenedor" style="background-color:rgb(55 65 81); width: 100%;  ">
                <div class="container-fluid">
                    <button class="navbar-toggler contenedor" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse contenedor " id="navbarSupportedContent" style=" background-color: rgb(55 65 81); width: 100% ">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 contenedor" style="height: 100%; width: 100%; padding-top:15px; padding-left: 15px">
                            <li class="nav-item ">
                                <span class="nav-link efecto " href="" style="letter-spacing: 8px; font-size: x-large; ">@Html.ActionLink("CLOTHES DATA", "Index", "Home", null, new { @class = "efecto", @style = "text-decoration:none; " }) </span>

                            </li>

                            <li class="nav-item">
                                <a class="nav-link popover-test" href="#" style="color: rgb(55 65 81); font-size: large; border-radius: 1%; border-image: initial; background-color: white; ">Bienvenido a ClothesDada</a>
                            </li>
     
                            <li class="nav-item dropdown">
                                <a style="color: white; font-size: large; padding-left: 15px;" class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Servicios
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" style="background-color: rgb(55 65 81); ">
                                    <li class="nav-item" style="background: rgb(55 65 81);">
                                        <a class="nav-link" href="@Url.Action("IndexProductos","Productos")" style="font-size: large; color: white; background-color: rgb(55 65 81); padding-left: 15px; ">Nuestros productos</a>
                                    </li>
                                    <li class="nav-item" style="background: rgb(55 65 81);">
                                        <a class="nav-link" href="@Url.Action("Reserva","ReservaDeHora")" style="font-size: large; color: white; background-color: rgb(55 65 81); padding-left: 15px; ">Reserva de ehora</a>
                                    </li>
                                </ul>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ServicioAlCliente","Home")" style="color: white; font-size: large; padding-left: 15px; ">Servicio al cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Contactenos","Contacto")" style=" color: white; font-size: large; padding-left: 15px;">Contáctenos</a>
                            </li>

                            <li class="nav-item" >
                                <div class="nav-link" href="" style=" color: white; padding-left: 100px; font-size: large; ">Bienvenido</div>
                                <div class="nav-link" href="" style=" color: white; padding-left: 90px; font-size: large;">@ViewBag.user</div>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer style="display: inline">

                <p style="display: inline">&copy; @DateTime.Now.Year - Tu mundo de confección, ClotesData</p>
                <a class="nav-link" href="@Url.Action("CerrarSesion","Acceso")" style="display: inline; color: white; font-size: x-large; padding-left: 57%"><marquee behavior="alternate" width="170" scrollamount="30" scrolldelay="500" >Cerrar Sessión </marquee></a>

            </footer>
        </div>

        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

Tienda/Views/Shared/_LayoutLoginAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>




    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    
    <header>
        
            <nav class="navbar navbar-expand-md navbar-light contenedor" style=" background-color:rgb(55 65 81); width: 100%; ">
                <div class="container-fluid">
                    <button class="navbar-toggler contenedor" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse contenedor " id="navbarSupportedContent" style=" background-color: rgb(55 65 81); width: 100% ">
                        <ul class="navbar-nav contenedor" style=" display: flex; justify-content: center; width: 100%; padding-top: 15px; padding-left: 15px">
                            <li class="nav-item ">
                                <span class="nav-link efecto " style="letter-spacing: 8px; font-size: x-large; ">@Html.ActionLink("CLOTHES DATA", "Index", "Home", null, new { @class = "efecto", @style = "text-decoration:none; " }) </span>

                            </li>

                            <li class="nav-item">
                                <a class="nav-link popover-test" href="#" style="color: rgb(55 65 81); font-size: large; border-radius: 1%; border-image: initial; background-color: white; ">Bienvenido a ClothesDada</a>
                            </li>
                            <li class="nav-item ">

                                <div class="nav-link " href="" style=" color: white; padding-left: 100px; font-size: large; ">Bienvenido</div>
                                <div class="nav-link" href="" style=" color: white; padding-left: 90px; font-size: large;">@ViewBag.admin</div>






                            </li>


                        </ul>
                    </div>
                </div>
            </nav>
     
    </header>
    

    <!--<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
        -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tu mundo de confección, ClotesData</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>

Tienda/Views/Shared/_LayoutRegistrarCliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>

    
    <div class="back">
        <header style="display:block">

            <nav class="navbar navbar-expand-md navbar-light contenedor" style="background-color:rgb(55 65 81); width: 100%; ">
                <div class="container-fluid">
                    <button class="navbar-toggler contenedor" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse contenedor " id="navbarSupportedContent" style=" background-color: rgb(55 65 81); width: 100% ">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 contenedor" style="height: 100%; width: 100%; padding-top: 15px; padding-left: 15px">
                            <li class="nav-item ">
                                <span class="nav-link efecto " href="" style="letter-spacing: 8px; font-size: x-large; ">@Html.ActionLink("CLOTHES DATA", "Index", "Home", null, new { @class = "efecto", @style = "text-decoration:none; " }) </span>

                            </li>

                            <li class="nav-item">
                                <a class="nav-link popover-test" href="#" style="color: rgb(55 65 81); font-size: large; border-radius: 1%; border-image: initial; background-color: white; ">Bienvenido a ClothesDada</a>
                            </li>
                            <!--<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false" style="color: white">
                                    Trabajos por Mecánico
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="gonzalo">Gonzalo Tobar (4)</a></li>
                                    <li><a class="dropdown-item" href="francisco">Francisco Sáez (4)</a></li>
                                    <li><a class="dropdown-item" href="guido">Guido Toro (3)</a></li>
                                </ul>
                            </li>-->
                            <li class="nav-item">
                                <a class="nav-link" href="contacto" style="font-size: large; color: white; padding-left: 20px ">Nuestros productos</a>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link Normal " href="" style=" padding-left: 20px; font-size: large; white-space: nowrap; padding-top: 13px">@Html.ActionLink("Contactenos", "ContactenosNoRegistrado", "Acceso", null, new { @class = "Normal", @style = "text-decoration:none; " })</span>
                            </li>

                            <li class="nav-item" style="white-space: nowrap;">

                                <a href='@Url.Action("Index", "Home")'>
                                    <img src='@Url.Content("~/Content/img/Volver.png")' style="width:190px; height: 40px; padding-left: 150px; white-space: nowrap;" />
                                </a>

                                <span class="nav-link Normal " href="" style="font-size: calc(1vw); padding-left: 130px; white-space: nowrap; ">Volver a inicio</span>



                                <!--<ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="font-size: 15px">


                                    <li><a class="dropdown-item" href="usuario">Empleado</a></li>
                                    <li><a class="dropdown-item" href="cliente">Cliente</a></li>
                                    <li><a class="dropdown-item" href="admin_login">Administrador</a></li>
                                </ul>-->
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!--<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
            -->
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>

                <p>&copy; @DateTime.Now.Year - Tu mundo de confección, ClotesData</p>
            </footer>
        </div>


        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

Tienda/Views/Shared/_LayoutServiciosRegistrado.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>

<body>


    <div class="back">
        <header style="display:block">

            <nav class="navbar navbar-expand-md navbar-light contenedor" style="background-color:rgb(55 65 81); width: 100%; ">
                <div class="container-fluid">
                    <button class="navbar-toggler contenedor" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse contenedor " id="navbarSupportedContent" style=" background-color: rgb(55 65 81); width: 100% ">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 contenedor" style="height: 100%; width: 100%; padding-top: 20px; padding-left: 15px">
                            <li class="nav-item ">
                                <span class="nav-link efecto " href="" style="letter-spacing: 8px; font-size: x-large; ">@Html.ActionLink("CLOTHES DATA", "Index", "Home", null, new { @class = "efecto", @style = "text-decoration:none; " }) </span>

                            </li>

                            <li class="nav-item">
                                <a class="nav-link popover-test" href="#" style="color: rgb(55 65 81); font-size: large; border-radius: 1%; border-image: initial; background-color: white; ">Bienvenido a ClothesDada</a>
                            </li>
                            <!--<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false" style="color: white">
                                    Trabajos por Mecánico
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="gonzalo">Gonzalo Tobar (4)</a></li>
                                    <li><a class="dropdown-item" href="francisco">Francisco Sáez (4)</a></li>
                                    <li><a class="dropdown-item" href="guido">Guido Toro (3)</a></li>
                                </ul>
                            </li>-->

                            <li class="nav-item dropdown">
                                <a style="color: white; font-size: large; padding-left: 15px;" class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Servicios
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" style="background-color: rgb(55 65 81); ">
                                    <li class="nav-item" style="background: rgb(55 65 81);">
                                        <a class="nav-link" href="contacto" style="font-size: large; color: white; background-color: rgb(55 65 81); padding-left: 15px; ">Nuestros productos</a>
                                    </li>
                                    <li class="nav-item" style="background: rgb(55 65 81);">
                                        <a class="nav-link" href="contacto" style="font-size: large; color: white; background-color: rgb(55 65 81); padding-left: 15px; ">Reserva de hora</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("ServicioAlCliente","Home")" style="color: white; font-size: large; padding-left: 10px; ">Servicio al cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Contactenos","Acceso")" style=" color: white; font-size: large; padding-left: 10px;">Contáctenos</a>
                            </li>

                            <li class="nav-item" style="white-space: nowrap;">

                                <a href='@Url.Action("IndexClienteLogeado", "Home")'>
                                    <img src='@Url.Content("~/Content/img/Volver.png")' style="width:190px; height: 40px; padding-left: 150px; white-space: nowrap;" />
                                </a>

                                <span class="nav-link Normal " href="" style="font-size: calc(1vw); padding-left: 130px; white-space: nowrap; ">Volver a inicio</span>



                                <!--<ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="font-size: 15px">


        <li><a class="dropdown-item" href="usuario">Empleado</a></li>
        <li><a class="dropdown-item" href="cliente">Cliente</a></li>
        <li><a class="dropdown-item" href="admin_login">Administrador</a></li>
    </ul>-->
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <!--<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
            -->
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer style="display: inline;">

                <p style="display: inline;"> &copy; @DateTime.Now.Year - Tu mundo de confección, ClotesData</p>
                <a class="nav-link" href="@Url.Action("CerrarSesion","Acceso")" style="display: inline; color: white; font-size: x-large; padding-left: 57%"><marquee behavior="alternate" width="170" scrollamount="40" scrolldelay="500">Cerrar Sessión </marquee></a>

            </footer>
        </div>

    
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>